### PR TITLE
Return a plain object to support Babel 6

### PR DESCRIPTION
**Pull request by thealjey**

### CODE REVIEW

**Comment by RReverser** [comment]
Just in case - I did see this PR, but deferred for now as it's a breaking change and, from what I see, most projects stick with Babel 5 for now due to that reason.

**Comment by barneycarroll** [comment]
@RReverser major version bump? This would prevent people dependent on the plugin in its current form from accidentally breaking with an innocent upgrade, and by keeping this as a separate branch, you could continue to patch, maintain and publish both versions, since the breaking change isn't that complex. We could supplement the README with an important notice to `npm install babel-plugin-uglify@">2.0.0"` for those who come to the project now yet intend to stick with Babel 5. This effectively means people can continue to benefit from maintenance without having even heard of Babel 6, and yet new users can benefit from a totally up to date plugin.

**Comment by Eschon** [comment]
:+1: for a major version bump
I'd really like to use this in my babel 6 project.

**Comment by RReverser** [comment]
Makes sense. If updating major version, then makes sense to also add options support I guess (for proper UglifyJS configuration).

**Comment by siuying** [comment]
Maybe just make it work on babel 6 first, and later add configuration?

**Comment by dbaba** [comment]
+1
Please fix this!

**Comment by neeharv** [comment]
@RReverser would love to use this - with a major version bump (which seems entirely fair, considering Babel's version jumped as well), shouldn't cause projects to break.

**Comment by jonathanong** [comment]
@RReverser are you going to release this?

**Comment by RReverser** [comment]
@jonathanong I'm afraid it's not that easy. Babel 6 "forked" the AST format into [its own](https://github.com/babel/babel/blob/master/doc/ast/spec.md), and isn't compatible with [ESTree](https://github.com/estree/estree) standard anymore. That means https://github.com/RReverser/babel-plugin-uglify/blob/master/src/index.js#L18 doesn't work that simply and requires extra conversion now. Until that's implemented, plugin will fail in Babel 6.

**Comment by jonathanong** [comment]
Ah ok. Good to know

**Pull request merged**
